bike:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100 
  
  rearWheel_jVel_controller:
    type: velocity_controllers/JointVelocityController
    joint: rear_wheel_joint
    # pid: {p: 0.0005, i: 0.00001,  d: 0.000001}
  rw_jVel_controller:
    type: velocity_controllers/JointVelocityController
    joint: rw_joint
    # pid: {p: 0.0005, i: 0.00001,  d: 0.000001}
  handle_jPos_controller:
    type: effort_controllers/JointPositionController
    joint: handle_joint
    pid: {p: 0.03, i: 0.001,  d: 0.0005}

  gazebo_ros_control:
      pid_gains:
          rear_wheel_joint:   {p: 0.01, i: 0.0001, d: 0.00002}
          rw_joint:  {p: 0.2, i: 0.001, d: 0.0001}
          # handle_joint: {p: 0.0005, i: 0.00001,  d: 0.000001}
